; Generated by AutoGUI 2.6.0
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui, Color, 000000
	Gui, Font, S12, Arial Black
	Gui +LastFound +AlwaysOnTop +ToolWindow -caption
	;; WinSet, TransColor, FFFFFF
    Gui, Margin, 0, 0
	Gui Add, Text, hWndhTxtText x0 y0 w42 h42 +0x200 +0x1, 12
	Gui, show, w42 h42, NoActivate, Overlay
	WinSet, ExStyle, +0x00000020, Overlay
	WinSet, Transparent, 100
    winmove, 600, 670